name: Update User Count

on:
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:
  push:
    branches: [ main, test, develop ]  
  pull_request:
    branches: [ main, test, develop ] 

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install mongodb
        
    - name: Update README with user count
      run: node .github/workflows/getUserCount.js  
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "Update user count"
        git push